name: "Deploy Datadog to Digital Ocean Kube"

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  datadog:
    name: 'datadog'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    # Install snap
    - name: Snapcraft Action
      uses: samuelmeuli/action-snapcraft@v2.1.1
    
    # Install Digital Ocean CLI
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
    # Install Helm
    - name: Install Helm
      run: sudo snap install helm --classic
      
    # Download Kubeval
    - name: Download Kubeval
      run: wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
      
    # Extract Kubeval
    - name: Extract Kubeval
      run: tar xf kubeval-linux-amd64.tar.gz
      
    # Install Kubeval
    - name: Install Kubeval
      run: sudo cp kubeval /usr/local/bin
      
    # Validate deployment file
    - name: Validate deployment file
      run: kubeval --ignore-missing-schemas deployment.yml
      working-directory: ./config/
      
    # Generate short term credentials to kube
    - name: Save DigitalOcean kubeconfig with short-lived credentials for cluster helpchain
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 helpchain

    # Create datadog secrets
    - name: Create datadog agent secrets in the cluster
      run: kubectl create secret generic datadog-secret --from-literal api-key=${{ secrets.DATADOG_API_KEY }} --from-literal app-key=${{ secrets.DATADOG_APP_KEY }}
      continue-on-error: true

    # Create datadog auth secret
    - name: Create datadog inter agent auth secret
      run: kubectl create secret generic datadog-auth-token --from-literal=token=${{ secrets.DATADOG_AUTH_SECRET }}
      continue-on-error: true

    # Create cluster-agent roles
    - name: Create kube cluster-agent roles
      run: kubectl apply -f "https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/cluster-agent-rbac.yaml"

    # Create RBAC roles
    - name: Create kube RBAC roles
      run: kubectl apply -f "https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/cluster-agent/rbac.yaml"
    
    # Deploy the datadog config to the kube service
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml

    - name: Verify deployment of deployment/datadog-cluster-agent
      run: kubectl rollout status deployment/datadog-cluster-agent